name: "More"

exports: "mootools-more.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools, The JavaScript framework"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[The MooTools development team](http://mootools.net/developers)"

sources:
  - "Source/Core/More.js"
  - "Source/Core/Lang.js"
  - "Source/Core/Log.js"
  - "Source/Core/Depender.js"
  - "Source/Class/Class.Refactor.js"
  - "Source/Class/Class.Binds.js"
  - "Source/Class/Class.Occlude.js"
  - "Source/Class/Chain.Wait.js"
  - "Source/Native/Array.Extras.js"
  - "Source/Native/Date.js"
  - "Source/Native/Date.Extras.js"
  - "Source/Native/Hash.Extras.js"
  - "Source/Native/String.Extras.js"
  - "Source/Native/String.QueryString.js"
  - "Source/Native/URI.js"
  - "Source/Native/URI.Relative.js"
  - "Source/Element/Element.Forms.js"
  - "Source/Element/Elements.From.js"
  - "Source/Element/Element.Delegation.js"
  - "Source/Element/Element.Measure.js"
  - "Source/Element/Element.Pin.js"
  - "Source/Element/Element.Position.js"
  - "Source/Element/Element.Shortcuts.js"
  - "Source/Forms/Form.Request.js"
  - "Source/Forms/Form.Request.Append.js"
  - "Source/Forms/Form.Validator.js"
  - "Source/Forms/Form.Validator.Inline.js"
  - "Source/Forms/Form.Validator.Extras.js"
  - "Source/Forms/OverText.js"
  - "Source/Fx/Fx.Elements.js"
  - "Source/Fx/Fx.Accordion.js"
  - "Source/Fx/Fx.Move.js"
  - "Source/Fx/Fx.Reveal.js"
  - "Source/Fx/Fx.Scroll.js"
  - "Source/Fx/Fx.Slide.js"
  - "Source/Fx/Fx.SmoothScroll.js"
  - "Source/Fx/Fx.Sort.js"
  - "Source/Drag/Drag.js"
  - "Source/Drag/Drag.Move.js"
  - "Source/Drag/Slider.js"
  - "Source/Drag/Sortables.js"
  - "Source/Request/Request.JSONP.js"
  - "Source/Request/Request.Queue.js"
  - "Source/Request/Request.Periodical.js"
  - "Source/Utilities/Assets.js"
  - "Source/Utilities/Color.js"
  - "Source/Utilities/Group.js"
  - "Source/Utilities/Hash.Cookie.js"
  - "Source/Utilities/IframeShim.js"
  - "Source/Interface/HtmlTable.js"
  - "Source/Interface/HtmlTable.Zebra.js"
  - "Source/Interface/HtmlTable.Sort.js"
  - "Source/Interface/HtmlTable.Select.js"
  - "Source/Interface/Keyboard.js"
  - "Source/Interface/Keyboard.Extras.js"
  - "Source/Interface/Mask.js"
  - "Source/Interface/Scroller.js"
  - "Source/Interface/Tips.js"
  - "Source/Interface/Spinner.js"

